export const SET_POPULATION = "SET_POPULATION";
export const SET_SICK_SPEED = "SET_SICK_SPEED";
export const SET_HEALTHY_SPEED = "SET_HEALTHY_SPEED";
export const SET_PERSON_RADIUS = "SET_PERSON_RADIUS";
export const SET_INFECTION_RADIUS = "SET_INFECTION_RADIUS";
export const SET_AVOIDANCE_RADIUS = "SET_AVOIDANCE_RADIUS";
