export const SET_POPULATION = "SET_POPULATION";
export const SET_SICK_SPEED = "SET_SICK_SPEED";
export const SET_AVOIDANCE_SPEED = "SET_AVOIDANCE_SPEED";
export const SET_HEALTHY_SPEED = "SET_HEALTHY_SPEED";
export const SET_PERSON_RADIUS = "SET_PERSON_RADIUS";
export const SET_INFECTION_RADIUS = "SET_INFECTION_RADIUS";
export const SET_AVOIDANCE_RADIUS = "SET_AVOIDANCE_RADIUS";

export const TOGGLE_INFECTION_RADIUS = "TOGGLE_INFECTION_RADIUS";
export const TOGGLE_AVOIDANCE_RADIUS = "TOGGLE_AVOIDANCE_RADIUS";

export const SET_SICKNESS_MORTALITY_RATE = "SET_SICKNESS_MORTALITY_RATE";
export const SET_SICKNESS_TOTAL_DURATION = "SET_SICKNESS_TOTAL_DURATION";
export const SET_SICKNESS_INCUBATION = "SET_SICKNESS_INCUBATION";
export const SET_SICKNESS_CONTAGIOUS = "SET_SICKNESS_CONTAGIOUS";